image: node:latest

stages:
  - test

test_api:
  stage: test
  script:
    - cd api
    - npm install
    - npm test
test_web:
  stage: test
  script:
    - cd web
    - npm install
    - npm test a
