version: '3.7'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: base

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    command: npm run dev
  #mongo
  mongo:
    container_name: mongodb
    build:
      context: ./mongo
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    command: [--auth]

  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
