version: '3.7'

services:
    ts-node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: ts-backend
        expose:
            - '4000'
        ports:
            - '4000:4000'
        command: npm run dev

    mongo:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
             - ./mongo-volume:/data/db
        ports:
            - 27017:27017
        command: [--auth]
