export interface IFilterData {
    commitment: string[] | null;
    occupation: string[] | null;
    graduation: string[] | null;
    course: string[] | null;
    country: string[] | null;
    semester: number | null;
    city: string[] | null;
    state: string[] | null;
    reference: string[] | null;
    nationality: string[] | null;
    religion: string[] | null;
    support: string[] | null;
    requirement: string[] | null;
    nationalityDetail: string[] | null;
    supportYet: string | null;
    age?: number | null;
    workExperience: number | null;
    sidejobHours: number | null;
    collageGrade: number | null;
    jobGrade: number | null;
    uniGrade: number | null;
}
